# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/affine-2.0.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/click-6.7-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/click-plugins-1.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cligj-0.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/curl-7.49.0-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/geos-3.5.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/geotiff-1.4.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/hdf4-4.2.12-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/hdf5-1.8.17-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jbig-2.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jpeg-8d-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/kealib-1.4.6-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgdal-2.1.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libnetcdf-4.4.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libtiff-4.0.6-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-2017.0.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numpy-1.12.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2k-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-9.0.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/proj4-4.9.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyparsing-2.1.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-3.5.3-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/rasterio-0.36.0-np112py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/setuptools-27.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/snuggs-1.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wheel-0.29.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xerces-c-3.1.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.2.2-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-3.tar.bz2
